{"links": {"self": {"href": "data/repositories/osrf/robocup3ds/pullrequests/45/comments/16371609.json"}, "html": {"href": "#!/osrf/robocup3ds/pull-requests/45/_/diff#comment-16371609"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 45, "links": {"self": {"href": "data/repositories/osrf/robocup3ds/pullrequests/45.json"}, "html": {"href": "#!/osrf/robocup3ds/pull-requests/45"}}, "title": "Gazebo7 support"}, "content": {"raw": "When I try to launch `gazebo-robocup3ds --verbose`, it says \n\n\"Warning: failed to find Gazebo's setup.sh.  You will need to source it manually. Afterwards, source share/robocup3ds/setup.sh again.\" \n\nand fails to load. Am I doing something wrong?", "markup": "markdown", "html": "<p>When I try to launch <code>gazebo-robocup3ds --verbose</code>, it says </p>\n<p>\"Warning: failed to find Gazebo's setup.sh.  You will need to source it manually. Afterwards, source share/robocup3ds/setup.sh again.\" </p>\n<p>and fails to load. Am I doing something wrong?</p>", "type": "rendered"}, "created_on": "2016-03-28T22:23:11.685984+00:00", "user": {"display_name": "Louise Poubel", "uuid": "{5cfa2075-477b-4ded-bdb9-8d2479544ec4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D"}, "html": {"href": "https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8/7d903d90-c5ea-4182-b7ef-0d467e9e1c74/128"}}, "nickname": "chapulina", "type": "user", "account_id": "557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8"}, "updated_on": "2016-03-28T22:23:11.688055+00:00", "type": "pullrequest_comment", "id": 16371609}