{"pagelen": 50, "values": [{"update": {"description": "This is a fix for the following problem:\r\n\r\n1. Compile and install the Swarm libraries.\r\n1. Compile and install the `example/` directory.\r\n1. Run gazebo (everything is OK):\r\n \r\n```\r\n#!python\r\n\r\ngazebo worlds/lost_person.world --verbose\r\n```\r\n\r\n1. Make some change in `example/LostPersonControllerPlugin.cc`.\r\n1. Recompile and install the `example/` directory.\r\n1. Run gazebo (you should get an error):\r\n \r\n```\r\n#!python\r\n\r\ngazebo worlds/lost_person.world --verbose\r\n```\r\nYou should get the following error:\r\n\r\n\r\n```\r\n#!python\r\n\r\n[Err] [Plugin.hh:165] Failed to load plugin libLostPersonControllerPlugin.so: /home/caguero/local/lib/libLostPersonControllerPlugin.so: undefined symbol: _ZN5swarm16LostPersonPlugin4LoadEN5boost10shared_ptrIN6gazebo7physics5ModelEEESt10shared_ptrIN3sdf7ElementEE\r\n```\r\n\r\nThis patch should fix it. ", "title": "Fix lost person problem", "destination": {"commit": {"hash": "6b98381fbe9a", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/swarm/commit/6b98381fbe9a.json"}, "html": {"href": "#!/osrf/swarm/commits/6b98381fbe9a"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/swarm.json"}, "html": {"href": "#!/osrf/swarm"}, "avatar": {"href": "data/bytebucket.org/ravatar/{06a294a4-4254-4f63-b7b3-e5768577fb96}ts=default"}}, "type": "repository", "name": "swarm", "full_name": "osrf/swarm", "uuid": "{06a294a4-4254-4f63-b7b3-e5768577fb96}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "d519c7293435", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/swarm/commit/d519c7293435.json"}, "html": {"href": "#!/osrf/swarm/commits/d519c7293435"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/swarm.json"}, "html": {"href": "#!/osrf/swarm"}, "avatar": {"href": "data/bytebucket.org/ravatar/{06a294a4-4254-4f63-b7b3-e5768577fb96}ts=default"}}, "type": "repository", "name": "swarm", "full_name": "osrf/swarm", "uuid": "{06a294a4-4254-4f63-b7b3-e5768577fb96}"}, "branch": {"name": "fix_lost_person"}}, "state": "MERGED", "author": {"display_name": "Carlos Ag\u00fcero", "uuid": "{da8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D"}, "html": {"href": "https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/692bf15758111acaddae4da15a47f9e5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCA-0.png"}}, "nickname": "caguero", "type": "user", "account_id": "557058:4ded1ddf-947e-4154-bbd1-3dba24f1bdbd"}, "date": "2015-11-16T22:36:49.936704+00:00"}, "pull_request": {"type": "pullrequest", "id": 79, "links": {"self": {"href": "data/repositories/osrf/swarm/pullrequests/79.json"}, "html": {"href": "#!/osrf/swarm/pull-requests/79"}}, "title": "Fix lost person problem"}}, {"approval": {"date": "2015-11-16T22:28:47.665051+00:00", "pullrequest": {"type": "pullrequest", "id": 79, "links": {"self": {"href": "data/repositories/osrf/swarm/pullrequests/79.json"}, "html": {"href": "#!/osrf/swarm/pull-requests/79"}}, "title": "Fix lost person problem"}, "user": {"display_name": "Nate Koenig", "uuid": "{c862cdd9-fcc8-4419-9fc7-e20db14b8fcb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D"}, "html": {"href": "https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:095b1e12-74ed-4e20-b44f-2f0745b616e0/ca24bb11-4787-4b14-a20d-d91835e9bde2/128"}}, "nickname": "Nathan Koenig", "type": "user", "account_id": "557058:095b1e12-74ed-4e20-b44f-2f0745b616e0"}}, "pull_request": {"type": "pullrequest", "id": 79, "links": {"self": {"href": "data/repositories/osrf/swarm/pullrequests/79.json"}, "html": {"href": "#!/osrf/swarm/pull-requests/79"}}, "title": "Fix lost person problem"}}, {"update": {"description": "This is a fix for the following problem:\r\n\r\n1. Compile and install the Swarm libraries.\r\n1. Compile and install the `example/` directory.\r\n1. Run gazebo (everything is OK):\r\n \r\n```\r\n#!python\r\n\r\ngazebo worlds/lost_person.world --verbose\r\n```\r\n\r\n1. Make some change in `example/LostPersonControllerPlugin.cc`.\r\n1. Recompile and install the `example/` directory.\r\n1. Run gazebo (you should get an error):\r\n \r\n```\r\n#!python\r\n\r\ngazebo worlds/lost_person.world --verbose\r\n```\r\nYou should get the following error:\r\n\r\n\r\n```\r\n#!python\r\n\r\n[Err] [Plugin.hh:165] Failed to load plugin libLostPersonControllerPlugin.so: /home/caguero/local/lib/libLostPersonControllerPlugin.so: undefined symbol: _ZN5swarm16LostPersonPlugin4LoadEN5boost10shared_ptrIN6gazebo7physics5ModelEEESt10shared_ptrIN3sdf7ElementEE\r\n```\r\n\r\nThis patch should fix it. ", "title": "Fix lost person problem", "destination": {"commit": {"hash": "d443630e7c35", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/swarm/commit/d443630e7c35.json"}, "html": {"href": "#!/osrf/swarm/commits/d443630e7c35"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/swarm.json"}, "html": {"href": "#!/osrf/swarm"}, "avatar": {"href": "data/bytebucket.org/ravatar/{06a294a4-4254-4f63-b7b3-e5768577fb96}ts=default"}}, "type": "repository", "name": "swarm", "full_name": "osrf/swarm", "uuid": "{06a294a4-4254-4f63-b7b3-e5768577fb96}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "d519c7293435", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/swarm/commit/d519c7293435.json"}, "html": {"href": "#!/osrf/swarm/commits/d519c7293435"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/swarm.json"}, "html": {"href": "#!/osrf/swarm"}, "avatar": {"href": "data/bytebucket.org/ravatar/{06a294a4-4254-4f63-b7b3-e5768577fb96}ts=default"}}, "type": "repository", "name": "swarm", "full_name": "osrf/swarm", "uuid": "{06a294a4-4254-4f63-b7b3-e5768577fb96}"}, "branch": {"name": "fix_lost_person"}}, "state": "OPEN", "author": {"display_name": "Carlos Ag\u00fcero", "uuid": "{da8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D"}, "html": {"href": "https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/692bf15758111acaddae4da15a47f9e5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCA-0.png"}}, "nickname": "caguero", "type": "user", "account_id": "557058:4ded1ddf-947e-4154-bbd1-3dba24f1bdbd"}, "date": "2015-11-13T22:02:12.731657+00:00"}, "pull_request": {"type": "pullrequest", "id": 79, "links": {"self": {"href": "data/repositories/osrf/swarm/pullrequests/79.json"}, "html": {"href": "#!/osrf/swarm/pull-requests/79"}}, "title": "Fix lost person problem"}}, {"update": {"description": "This is a fix for the following problem:\r\n\r\n1. Compile and install the Swarm libraries.\r\n1. Compile and install the `example/` directory.\r\n1. Run gazebo (everything is OK):\r\n \r\n```\r\n#!python\r\n\r\ngazebo worlds/lost_person.world --verbose\r\n```\r\n\r\n1. Make some change in `example/LostPersonControllerPlugin.cc`.\r\n1. Recompile and install the `example/` directory.\r\n1. Run gazebo (you should get an error):\r\n \r\n```\r\n#!python\r\n\r\ngazebo worlds/lost_person.world --verbose\r\n```\r\nYou should get the following error:\r\n\r\n\r\n```\r\n#!python\r\n\r\n[Err] [Plugin.hh:165] Failed to load plugin libLostPersonControllerPlugin.so: /home/caguero/local/lib/libLostPersonControllerPlugin.so: undefined symbol: _ZN5swarm16LostPersonPlugin4LoadEN5boost10shared_ptrIN6gazebo7physics5ModelEEESt10shared_ptrIN3sdf7ElementEE\r\n```\r\n\r\nThis patch should fix it. ", "title": "Fix lost person problem", "destination": {"commit": {"hash": "d443630e7c35", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/swarm/commit/d443630e7c35.json"}, "html": {"href": "#!/osrf/swarm/commits/d443630e7c35"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/swarm.json"}, "html": {"href": "#!/osrf/swarm"}, "avatar": {"href": "data/bytebucket.org/ravatar/{06a294a4-4254-4f63-b7b3-e5768577fb96}ts=default"}}, "type": "repository", "name": "swarm", "full_name": "osrf/swarm", "uuid": "{06a294a4-4254-4f63-b7b3-e5768577fb96}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "d519c7293435", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/swarm/commit/d519c7293435.json"}, "html": {"href": "#!/osrf/swarm/commits/d519c7293435"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/swarm.json"}, "html": {"href": "#!/osrf/swarm"}, "avatar": {"href": "data/bytebucket.org/ravatar/{06a294a4-4254-4f63-b7b3-e5768577fb96}ts=default"}}, "type": "repository", "name": "swarm", "full_name": "osrf/swarm", "uuid": "{06a294a4-4254-4f63-b7b3-e5768577fb96}"}, "branch": {"name": "fix_lost_person"}}, "state": "OPEN", "author": {"display_name": "Carlos Ag\u00fcero", "uuid": "{da8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D"}, "html": {"href": "https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/692bf15758111acaddae4da15a47f9e5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCA-0.png"}}, "nickname": "caguero", "type": "user", "account_id": "557058:4ded1ddf-947e-4154-bbd1-3dba24f1bdbd"}, "date": "2015-11-13T22:02:12.715034+00:00"}, "pull_request": {"type": "pullrequest", "id": 79, "links": {"self": {"href": "data/repositories/osrf/swarm/pullrequests/79.json"}, "html": {"href": "#!/osrf/swarm/pull-requests/79"}}, "title": "Fix lost person problem"}}]}